FROM python:3.5-alpine3.7

COPY . /WORKDIR/
WORKDIR /WORKDIR

RUN sed -i 's/http\:\/\/dl-cdn.alpinelinux.org/https\:\/\/alpine.global.ssl.fastly.net/g' /etc/apk/repositories
RUN apk update
RUN apk add --virtual .build-deps gcc build-base python3-dev libffi-dev openssl-dev linux-headers && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apk/*

RUN pip3 install -U pip -r requirements.txt

ENTRYPOINT ["python3.5", "pyreq.py"]
